In [1]:
import numpy as np

In [5]:
joao_pts = [30, 40, 15]
pedro_pts = [100, 24, 48, 23]
maria_pts = [92, 22, 34, 12]
marcos_pts = [12, 34, 12,43]
pontos = np.array([joao_pts, pedro_pts, maria_pts, marcos_pts])

In [6]:
pontos

array([list([30, 40, 15]), list([100, 24, 48, 23]),
       list([92, 22, 34, 12]), list([12, 34, 12, 43])], dtype=object)

In [7]:
pontos[0]

[30, 40, 15]

In [8]:
pontos[1][0]

100

In [10]:
my_data = np.arange(0, 20)
print(my_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [11]:
mat1 = np.reshape(my_data, (5,4))
print(mat1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [13]:
print(mat1[2][2])

10


In [17]:
m1 = ['Python', 'C#', 'Julia']
m2 = [20, 7, 2015]
m3 = ['Miguel','Mabel', 'Gilete']
[m1,m2,m3]

[['Python', 'C#', 'Julia'], [20, 7, 2015], ['Miguel', 'Mabel', 'Gilete']]

In [18]:
np.array([m1,m2,m3])

array([['Python', 'C#', 'Julia'],
       ['20', '7', '2015'],
       ['Miguel', 'Mabel', 'Gilete']], dtype='<U6')